[package]
name = "num-primitive"
version = "0.3.9"
description = "Traits for primitive numeric types"
repository = "https://github.com/rust-num/num-primitive"
license = "MIT OR Apache-2.0"
keywords = ["generic", "mathematics", "numerics", "primitive"]
categories = ["algorithms", "science", "no-std"]
edition = "2024"
rust-version = "1.98"

[package.metadata.release]
allow-branch = ["main"]
sign-tag = true

[features]
default = ["std"]
std = []

[lints.rust]
missing_docs = "deny"
private_bounds = "deny"
private_interfaces = "deny"
unconditional_recursion = "deny"
unnameable_types = "deny"
unreachable_pub = "deny"

[lints.rustdoc]
broken_intra_doc_links = "deny"
private_intra_doc_links = "deny"
